/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class media_module_codec_amr_AmrManager */

#ifndef _Included_media_module_codec_amr_AmrManager
#define _Included_media_module_codec_amr_AmrManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    enc_amrnb
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_media_module_codec_amr_AmrManager_enc_1amrnb
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    start_enc_amrnb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_start_1enc_1amrnb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    stop_enc_amrnb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_stop_1enc_1amrnb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    dec_amrnb
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_media_module_codec_amr_AmrManager_dec_1amrnb
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    start_dec_amrnb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_start_1dec_1amrnb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    stop_dec_amrnb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_stop_1dec_1amrnb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    enc_amrwb
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_media_module_codec_amr_AmrManager_enc_1amrwb
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    start_enc_amrwb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_start_1enc_1amrwb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    stop_enc_amrwb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_stop_1enc_1amrwb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    dec_amrwb
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_media_module_codec_amr_AmrManager_dec_1amrwb
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    start_dec_amrwb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_start_1dec_1amrwb
  (JNIEnv *, jobject);

/*
 * Class:     media_module_codec_amr_AmrManager
 * Method:    stop_dec_amrwb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_module_codec_amr_AmrManager_stop_1dec_1amrwb
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
